### ISSUE TITLE
How can we use Kops CNI - Cilium and Calico with acceleration in China?

### ISSUE THREAD

**Issue by brant4test** [pahud/kops-bjs#18]
Hi, Pahud,

From the doc [here](https://github.com/pahud/kops-bjs/tree/master/bjs-fastboot), 
“
export CNI_VERSION_URL env variable and point to Beijing S3 for CNI plug-in download acceleration
”
 
Where’s the location for Cilium CNI for Kops? How to use CNI_VERSION_URL?  Thanks!

Btw is the default CNI - kubenet the only option for now? 

If I set CNI = cilium, 
$ vi create_cluster_localmirror.sh
--networking=cilium
$ bash create_cluster_localmirror.sh
```
I0711 08:55:30.386964   22397 create_cluster.go:1318] Using SSH public key: /home/kops/.ssh/id_rsa.pub
I0711 08:55:33.030179   22397 create_cluster.go:472] Inferred --cloud=aws from zone "cn-north-1a"
W0711 08:55:33.030257   22397 create_cluster.go:648] Running with masters in the same AZs; redundancy will be reduced
I0711 08:55:33.373778   22397 subnets.go:184] Assigned CIDR 10.36.8.0/21 to subnet cn-north-1a
I0711 08:55:33.373815   22397 subnets.go:184] Assigned CIDR 10.36.16.0/21 to subnet cn-north-1b
panic: semver: Parse(https://s3.cn-north-1.amazonaws.com.cn/kubernetes-release/release/v1.9.6): Invalid character(s) found in major number "https://s3"
 
goroutine 1 [running]:
k8s.io/kops/vendor/github.com/blang/semver.MustParse(0x7fff9f76c559, 0x48, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
               /go/src/k8s.io/kops/vendor/github.com/blang/semver/semver.go:319 +0x202
k8s.io/kops/pkg/apis/kops/validation.validateCilium(0xc42043e000, 0x9)
               /go/src/k8s.io/kops/pkg/apis/kops/validation/legacy.go:631 +0x119
k8s.io/kops/pkg/apis/kops/validation.ValidateCluster(0xc42043e000, 0xc420fca500, 0x18)
               /go/src/k8s.io/kops/pkg/apis/kops/validation/legacy.go:504 +0x1aa0
k8s.io/kops/pkg/apis/kops/validation.DeepValidate(0xc42043e000, 0xc420f61f60, 0x4, 0x4, 0x0, 0x4, 0x4)
               /go/src/k8s.io/kops/pkg/apis/kops/validation/legacy.go:646 +0x3b
main.RunCreateCluster(0xc42000b940, 0x4fafc20, 0xc42006a008, 0xc420704700, 0x0, 0x0)
               /go/src/k8s.io/kops/cmd/kops/create_cluster.go:1058 +0x3295
main.NewCmdCreateCluster.func1(0xc420494b40, 0xc42098b500, 0x0, 0x17)
               /go/src/k8s.io/kops/cmd/kops/create_cluster.go:249 +0x1c9
k8s.io/kops/vendor/github.com/spf13/cobra.(*Command).execute(0xc420494b40, 0xc42098b380, 0x17, 0x18, 0xc420494b40, 0xc42098b380)
               /go/src/k8s.io/kops/vendor/github.com/spf13/cobra/command.go:603 +0x234
k8s.io/kops/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x51fc300, 0x2b34100, 0x0, 0x0)
               /go/src/k8s.io/kops/vendor/github.com/spf13/cobra/command.go:689 +0x2fe
k8s.io/kops/vendor/github.com/spf13/cobra.(*Command).Execute(0x51fc300, 0x5231138, 0x0)
               /go/src/k8s.io/kops/vendor/github.com/spf13/cobra/command.go:648 +0x2b
main.Execute()
               /go/src/k8s.io/kops/cmd/kops/root.go:94 +0x91
main.main()
               /go/src/k8s.io/kops/cmd/kops/main.go:25 +0x20
```

If I set CNI = calico, 
$ vi create_cluster_localmirror.sh
--networking calico
Calico images are very hard to pull without acceleration ( half an hour passed, still cannot see success)

![image](https://user-images.githubusercontent.com/7472674/42576868-ecc9c3d4-8555-11e8-9221-607b7ba13e2b.png)

**Comment by pahud** [comment]
`CNI_VERSION_URL` is an override of CNI URL.

check the following URLs
https://github.com/kubernetes/kops/blob/fc1bed435368608a2817114a1e3c01b8d79df762/upup/pkg/fi/cloudup/networking.go
https://github.com/kubernetes/kops/blob/e9b6a4544ef5f88ab155c319cabd5518c77ba4c8/docs/aws-china.md

If you need to use other CNI alternatives, I think you need

1) figure out where is the original CNI file
2) what is the hash string

then you can edit the `create_cluster_localmirror.sh` file and update the `CNI_VERSION_URL` and `CNI_ASSET_HASH_STRING` variables and hopefully you will be able to use the CNI drivers.

We have not yet tested other CNIs and `amazon-k8s-cni`(https://github.com/pahud/kops-bjs/issues/17) would be our next priority to go.

If you figure out how to set those variables to make other CNI work, please let us know.
